spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://你的IP:3306/big_event
    username: root
    password: 你的密码
  #    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  mail:

    username: putileaf@foxmail.com
    password: 你的密码
    host: smtp.qq.com

#开启驼峰命名和下划线命名的自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true

