spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/127.0.1:3306/healthyify
    username: root

    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  mail:

    username: 
    password: 
    host: smtp.qq.com


#开启驼峰命名和下划线命名的自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true

